import 'package:flutter/material.dart';
import 'package:material_ui/material_ui.dart' as material;

/// dynamic_color 2 uses material_ui types; the app still uses Flutter widgets.
/// Copy the current color roles without reseeding the device palette.
ColorScheme? flutterDynamicColors(material.ColorScheme? colors) {
  if (colors == null) return null;
  return ColorScheme(
    brightness: colors.brightness,
    primary: colors.primary,
    onPrimary: colors.onPrimary,
    primaryContainer: colors.primaryContainer,
    onPrimaryContainer: colors.onPrimaryContainer,
    primaryFixed: colors.primaryFixed,
    primaryFixedDim: colors.primaryFixedDim,
    onPrimaryFixed: colors.onPrimaryFixed,
    onPrimaryFixedVariant: colors.onPrimaryFixedVariant,
    secondary: colors.secondary,
    onSecondary: colors.onSecondary,
    secondaryContainer: colors.secondaryContainer,
    onSecondaryContainer: colors.onSecondaryContainer,
    secondaryFixed: colors.secondaryFixed,
    secondaryFixedDim: colors.secondaryFixedDim,
    onSecondaryFixed: colors.onSecondaryFixed,
    onSecondaryFixedVariant: colors.onSecondaryFixedVariant,
    tertiary: colors.tertiary,
    onTertiary: colors.onTertiary,
    tertiaryContainer: colors.tertiaryContainer,
    onTertiaryContainer: colors.onTertiaryContainer,
    tertiaryFixed: colors.tertiaryFixed,
    tertiaryFixedDim: colors.tertiaryFixedDim,
    onTertiaryFixed: colors.onTertiaryFixed,
    onTertiaryFixedVariant: colors.onTertiaryFixedVariant,
    error: colors.error,
    onError: colors.onError,
    errorContainer: colors.errorContainer,
    onErrorContainer: colors.onErrorContainer,
    surface: colors.surface,
    onSurface: colors.onSurface,
    surfaceDim: colors.surfaceDim,
    surfaceBright: colors.surfaceBright,
    surfaceContainerLowest: colors.surfaceContainerLowest,
    surfaceContainerLow: colors.surfaceContainerLow,
    surfaceContainer: colors.surfaceContainer,
    surfaceContainerHigh: colors.surfaceContainerHigh,
    surfaceContainerHighest: colors.surfaceContainerHighest,
    onSurfaceVariant: colors.onSurfaceVariant,
    outline: colors.outline,
    outlineVariant: colors.outlineVariant,
    shadow: colors.shadow,
    scrim: colors.scrim,
    inverseSurface: colors.inverseSurface,
    onInverseSurface: colors.onInverseSurface,
    inversePrimary: colors.inversePrimary,
    surfaceTint: colors.surfaceTint,
  );
}
